### ISSUE TITLE
DBの設計

### ISSUE THREAD

**Issue by MasatoIso** [MasatoIso/welfare-service#10]
現段階ではDBを施設のテーブルだけでよいと考えております。
何か追加すべき項目はありますでしょうか。ご確認お願いいたします。

facilityテーブル
- name : string
- location : string
- phone_number : varchar

**Comment by S-H-GAMELINKS** [comment]
`location`のほかに経度と緯度の情報も必要ではないでしょうか？

また、施設自体の営業時間などの備考情報も別途必要と考えます
いかがでしょうか？

**Comment by MasatoIso** [comment]
緯度　lat:float
　　経度  lng:float
	営業時間  business hours:string
	面会時間 visiting hours:string

も追加します。

**Comment by MasatoIso** [comment]
phone_numberの型をstring に変更します。

**Comment by MasatoIso** [comment]
#13 で実装済
