### ISSUE TITLE
デザインのモックを作成する

### ISSUE THREAD

**Issue by MasatoIso** [MasatoIso/welfare-service#9]
index, about, contactページのデザインのモックを作成します。

- [x] index
- [x] about
- [x] contact
- [x] facilities
- [x] 施設詳細ページ

**Comment by MasatoIso** [comment]
とりあえず簡単に作成してみました。

index: [Index.pdf](https://github.com/MasatoIso/welfare-service/files/3388567/Index.pdf)
about: [About.pdf](https://github.com/MasatoIso/welfare-service/files/3388568/About.pdf)
contact: [Contact.pdf](https://github.com/MasatoIso/welfare-service/files/3388569/Contact.pdf)

**Comment by S-H-GAMELINKS** [comment]
デザイン、確認致しました

モックの作成を進めていただければと思います

**Comment by MasatoIso** [comment]
夜遅くに失礼します。
残りのデザインのモックです。
ご確認お願いいたします。

Index
[Index.pdf](https://github.com/MasatoIso/welfare-service/files/3411437/Index.pdf)
About
[About.pdf](https://github.com/MasatoIso/welfare-service/files/3411433/About.pdf)
Facilities(一覧ページ)
[facilities.pdf](https://github.com/MasatoIso/welfare-service/files/3411436/facilities.pdf)

**Comment by S-H-GAMELINKS** [comment]
ありがとうございます！
確認させて頂きました！

モックはこれでOKだと思います
